name: ci

on:
  push:
  pull_request:

jobs:
  rust:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: cargo test --workspace --all-features
      - run: cargo clippy --workspace --all-targets -D warnings
      - run: cargo fmt --all -- --check
